### ISSUE TITLE
Will not build

### ISSUE THREAD

**Issue by jbreadtoasted** [KettleFoundation/Kettle-1.14.4#1]
Can you add a released jar please this would be an awesome thing to have for a 1.14.4. forge server

**Comment by mpfaff** [comment]
Can you give *any* information about what happens?

**Comment by jbreadtoasted** [comment]
It says it has deprecated methods and wont build

**Comment by jbreadtoasted** [comment]
@mpfaff  Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s

C:\Users\jbrea\Desktop\New folder (2)\Kettle-1.14.4-master>
