### ISSUE TITLE
fix please

### ISSUE THREAD

**Issue by LeePC** [KettleFoundation/Kettle-1.14.4#3]
> Task :kettle:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kettle:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with
Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:comman
d_line_warnings

BUILD FAILED in 1m 24s
5 actionable tasks: 5 executed

**Comment by LeePC** [comment]
[error.txt](https://github.com/KettleFoundation/Kettle-1.14.4/files/3888418/error.txt)
error file log

**Comment by GMatrixGames** [comment]
There is no source to build.

**Comment by LeePC** [comment]
> There is no source to build.

?????
What do you mean?? Source files obviously used the public
